### ISSUE TITLE
Linux portable mode cannot find libglfw3

### ISSUE THREAD

**Issue by Hideman85** [PolyMC/PolyMC#1544]
### Operating System

Linux

### Version of PolyMC

5.0

### Version of Qt

5.15.6

### Description of bug

It does not locate the libglfw3 native, I checked it extract well in the instance natives folder but the game do not load it.
I tried to switch to system lib (libglfw3-wayland) no more success.
I am using Ubuntu 22.10 on wayland

### Steps to reproduce

Just start a minecraft version 1.18.2

### Suspected cause

No really idea, tried the two way none worked...

Log:

```
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: libglfw.so
	at org.lwjgl.system.Library.loadNative(Library.java:299) ~[lwjgl-3.2.2.jar%235!/:build 10] {}
	at org.lwjgl.system.Library.loadNative(Library.java:205) ~[lwjgl-3.2.2.jar%235!/:build 10] {}
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:674) ~[lwjgl-glfw-3.2.2.jar%230!/:build 10] {re:mixin}
```

I just seen the following log:
```
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
```
I would have a look at it later, if you have already got similar issue I would be grateful of some help 🙂

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Hideman85** [comment]
In PolyMC forcing the version of LWJGL3 to 3.3.1 instead of the one predefined fix the error for me.

Hope this helps the next one 😉

**Comment by LennyMcLennington** [comment]
This shouldn't be happening, but I can't reproduce the issue. Can you post the PolyMC-0.log file from `~/.local/share/PolyMC`? (or `~/.var/app/org.polymc.PolyMC/data/PolyMC` if you're on flatpak)
