### ISSUE TITLE
Jemalloc support

### ISSUE THREAD

**Issue by System64fumo** [PolyMC/PolyMC#1579]
### Operating System

Linux

### Version of PolyMC

Version: 5.1
Commit: 59fa701c2475c6017780d14f60c7b35f67a25ec4
Channel: 59fa701c

### Version of Qt

Qt 6.5.0

### Description of bug

Running polymc on asahi linux (arch linux arm) fails to launch the game due to jemalloc not supporting 16k pages
However launching minecraft from prismlauncher works just fine?

The bug in question: <jemalloc>: Unsupported system page size

### Steps to reproduce

Steps to get the error:
Install polymc from aur (polymc not polymc-git)
Create an instance of minecraft 1.18.2
Select any appropiate version of java
Launch
\<jemalloc\>: Unsupported system page size
\<jemalloc\>: Unsupported system page size

Steps to not get the error:
Install prismlauncher from aur
Create an instance of minecraft 1.18.2
Select an appropiate version of java
Launch
Works just fine

### Suspected cause

well the logs say "\<jemalloc\>: Unsupported system page size" twice and asahi linux documentation clearly says that jemalloc is non functional
But despite that
Prismlauncher works just fine????

So if i had to guess prismlauncher uses different jemalloc?
Maybe it compiles it with custom 16k patches?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jdpatdiscord** [comment]
I suppose I'm the only one around here with test hardware to bother with this. But I do not have Asahi installed.
Have you made any attempts to fix this yourself / figure out where to start?

**Comment by HeyaGlitz** [comment]
It could possibly be an issue with Java, could you post the full log when you launch with PolyMC? (and maybe a log from Prism, it *could* contain some debug info, just to be on the safe side ;)

**Comment by System64fumo** [comment]
I have not made any attempts to fix it other than trying what worked before (using prism launcher)
I don't really have any idea on where to start other than guessing (That being said there's probably a custom version of jemalloc used in prismlauncher, but what do i know)
Sorry :P

Guesses:
/home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2-gman64.1/lwjgl-jemalloc-3.2.2-gman64.1.jar
/home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2-gman64.1/lwjgl-jemalloc-3.2.2-gman64.1-natives-linux-arm64.jar

This is the game log
```
PolyMC version: 5.1


Launched instance in online mode

authserver.mojang.com resolves to:
    [13.226.2.7, 13.226.2.28, 13.226.2.71, 13.226.2.47, ::]

session.minecraft.net resolves to:
    [13.107.213.43, 13.107.246.43, 2620:1ec:bdf::43, 2620:1ec:46::43]

textures.minecraft.net resolves to:
    [13.107.237.43, 13.107.238.43, 2620:1ec:4f:1::43, 2620:1ec:4e:1::43]

api.mojang.com resolves to:
    [13.107.246.43, 13.107.213.43, 2620:1ec:46::43, 2620:1ec:bdf::43]


Minecraft folder is:
/home/amir/.local/share/PolyMC/instances/default/.minecraft


Java path is:
/usr/lib/jvm/java-17-openjdk/bin/java


Checking Java version...
Java is version 17.0.7, using 64 (aarch64) architecture, from N/A.


Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/amir/.local/share/PolyMC/instances/default/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Using system OpenAL.
Using system GLFW.

Libraries:
  /home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2-gman64.1/lwjgl-glfw-3.2.2-gman64.1.jar
  /home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2-gman64.1/lwjgl-jemalloc-3.2.2-gman64.1.jar
  /home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl-openal/3.2.2-gman64.1/lwjgl-openal-3.2.2-gman64.1.jar
  /home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2-gman64.1/lwjgl-opengl-3.2.2-gman64.1.jar
  /home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl-stb/3.2.2-gman64.1/lwjgl-stb-3.2.2-gman64.1.jar
  /home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl/3.2.2-gman64.1/lwjgl-3.2.2-gman64.1.jar
  /home/amir/.local/share/PolyMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /home/amir/.local/share/PolyMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/amir/.local/share/PolyMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/amir/.local/share/PolyMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /home/amir/.local/share/PolyMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /home/amir/.local/share/PolyMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /home/amir/.local/share/PolyMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/amir/.local/share/PolyMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.1/log4j-slf4j18-impl-2.17.1.jar
  /home/amir/.local/share/PolyMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /home/amir/.local/share/PolyMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /home/amir/.local/share/PolyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/amir/.local/share/PolyMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  /home/amir/.local/share/PolyMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/amir/.local/share/PolyMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/amir/.local/share/PolyMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/amir/.local/share/PolyMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/amir/.local/share/PolyMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/amir/.local/share/PolyMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/amir/.local/share/PolyMC/libraries/com/mojang/datafixerupper/4.1.27/datafixerupper-4.1.27.jar
  /home/amir/.local/share/PolyMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /home/amir/.local/share/PolyMC/libraries/com/mojang/authlib/3.3.39/authlib-3.3.39.jar
  /home/amir/.local/share/PolyMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/amir/.local/share/PolyMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/amir/.local/share/PolyMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/amir/.local/share/PolyMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /home/amir/.local/share/PolyMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /home/amir/.local/share/PolyMC/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  /home/amir/.local/share/PolyMC/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  /home/amir/.local/share/PolyMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /home/amir/.local/share/PolyMC/libraries/com/mojang/minecraft/1.18.2/minecraft-1.18.2-client.jar

Native libraries:
  /home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2-gman64.1/lwjgl-glfw-3.2.2-gman64.1-natives-linux-arm64.jar
  /home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2-gman64.1/lwjgl-jemalloc-3.2.2-gman64.1-natives-linux-arm64.jar
  /home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl-openal/3.2.2-gman64.1/lwjgl-openal-3.2.2-gman64.1-natives-linux-arm64.jar
  /home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2-gman64.1/lwjgl-opengl-3.2.2-gman64.1-natives-linux-arm64.jar
  /home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl-stb/3.2.2-gman64.1/lwjgl-stb-3.2.2-gman64.1-natives-linux-arm64.jar
  /home/amir/.local/share/PolyMC/libraries/org/lwjgl/lwjgl/3.2.2-gman64.1/lwjgl-3.2.2-gman64.1-natives-linux-arm64.jar

Params:
  --username  --version 1.18.2 --gameDir /home/amir/.local/share/PolyMC/instances/default/.minecraft --assetsDir /home/amir/.local/share/PolyMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms1024m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 1162


<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
May 28, 2023 5:42:31 AM org.polymc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at ac.a(SourceFile:65)
	at dyr.a(SourceFile:2394)
	at dyr.a(SourceFile:2389)
	at net.minecraft.client.main.Main.main(SourceFile:206)
	... 9 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.OutOfMemoryError: Failed to allocate 12582912 bytes [in thread "Render thread"]
	at dsk.a(SourceFile:13)
	at dth.<init>(SourceFile:56)
	at dto.<init>(SourceFile:19)
	at dto.<init>(SourceFile:23)
	at dto.<clinit>(SourceFile:11)
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:46)
	at net.minecraft.client.main.Main.main(SourceFile:194)
	... 9 more
May 28, 2023 5:42:31 AM org.polymc.EntryPoint main
INFO: Exiting with 1
Process exited with code 1.
Clipboard copy at: 28 May 2023 05:42:35 +0300

```

**Comment by HeyaGlitz** [comment]
https://github.com/PrismLauncher/meta/commit/f5534daefe939c058c6e724e51932737b3cc514c
You were correct, they use a self-compiled version of Jemalloc specifically to make it work on Asahi lol
@jdpatdiscord

**Comment by System64fumo** [comment]
Should i make a PR for this?

**Comment by HeyaGlitz** [comment]
Sure

**Comment by slendidev** [comment]
Go for it.

**Comment by System64fumo** [comment]
Slight problem..
Polymc does not have a patches thing.
My current solution would assume that all linux-arm64 devices require the patched libraries.
Which for me on my m2 mac works just fine, But i don't know how well that would go for other systems.

Should do it this way or wait until someone else with a brighter and better idea does it?

**Comment by HeyaGlitz** [comment]
I feared that may be the issue, and it wouldn't be quite a simple PR as it would also require quite a bit of work on the launcher itself. Applying the patched version to everyone using Linux shouldn't be a problem I believe (edit: Linux aarch64) Should test it sometime and we can continue then.

**Comment by System64fumo** [comment]
To everyone using linux-aarch64 which is less of a problem.
But ig it wouldn't hurt as much?
I could test this on another aarch64 system i have (Raspberry pi) and see if it breaks it or not.
Hopefully all goes well?

Edit:

Or until something gets addressed a temporary fix could be to make lwjgl 3.3.1 grab the patched files.
Sure it's not perfect but it would let asahi users play without having to fiddle with editing it manually,
Let me know cause this sounds stupid lol

**Comment by System64fumo** [comment]
This project is inactive..
