### ISSUE TITLE
Unable to detect the forge installer

### ISSUE THREAD

**Issue by briermay** [PolyMC/PolyMC#1646]
### Operating System

Windows

### Version of PolyMC

6.1

### Version of Qt

6.6.1

### Description of bug

some packs will not launch with an error about not being able to detect forge

from log:
Mar 04, 2024 11:49:32 AM org.polymc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:157)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38)
	... 9 more
Mar 04, 2024 11:49:32 AM org.polymc.EntryPoint main
INFO: Exiting with 1
Process exited with code 1.

and before anyone decides to play the "its not a PolyMC issue" game, I have 0 issues with MultiMC, or Prism Launcher with the same exact modpack and same exact java install. so its is definitely something related to PolyMC

### Steps to reproduce

Install several packs including but not limited to All the Mods 8 (not sure all the ones that are effected)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by HeyaGlitz** [comment]
https://github.com/PolyMC/PolyMC/issues/1638#issuecomment-1959641318
Have you already tried this?

**Comment by briermay** [comment]
ok that seems to have fixed it for now, but curious as to why I had to do that. as an end user I should never have to touch anything in the appdata folder (messing with that folder can severly cripple a windows install). one thing that wierdly was working in the meantime, was editing the instance and bumping the installed forge sub version up to the next release which was tedius so why I posted the issue.

**Comment by HeyaGlitz** [comment]
Forge recently updated all of their installers, causing a hash mismatch. The launcher has weird caching so that's why you had to delete the folder.

**Comment by briermay** [comment]
that makes no sense to me as it was happening in older versions like 1.19, 1.18 even, so them updating their launcher should not have affected ones that old imo. but anyhow thanks for the fix.

**Comment by LennyMcLennington** [comment]
> that makes no sense to me as it was happening in older versions like 1.19, 1.18 even, so them updating their launcher should not have affected ones that old imo. but anyhow thanks for the fix.

Forge updated all of their installers, as in they replaced the files for every forge installer since around 1.16 iirc, so all of those had mismatches.
