### ISSUE TITLE
Any version above 1.20.3 won't work

### ISSUE THREAD

**Issue by Jeffllama123** [PolyMC/PolyMC#1656]
### Version of PolyMC

Polymc 6.1

### Version of Qt

Qt 5/6

### Description of bug

I try to launch a version 1.20.3 or above, i specifically tried 1.20.4, i also tried .5 and .6, but when I launch, I get this error:

[00:48:42] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 101 milliseconds
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
May 21, 2024 12:48:43 AM org.polymc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at ab.a(SourceFile:66)
	at evi.a(SourceFile:2605)
	at evi.a(SourceFile:2580)
	at net.minecraft.client.main.Main.main(SourceFile:233)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 6 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib [in thread "Render thread"]
	at org.lwjgl.system.Library.loadSystem(Library.java:174)
	at org.lwjgl.system.Library.loadSystem(Library.java:64)
	at org.lwjgl.system.Library.<clinit>(Library.java:52)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
	at eoz.<clinit>(SourceFile:8)
	at epw.<init>(SourceFile:49)
	at eqd.<init>(SourceFile:33)
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:51)
	at net.minecraft.client.main.Main.main(SourceFile:220)
	... 7 more
May 21, 2024 12:48:43 AM org.polymc.EntryPoint main
INFO: Exiting with 1
Process exited with code 1.

### Steps to reproduce

1. create an instance 1.20.3-1.20.6
2. run instance
3. cry as you arent smart enough to fix it

### Suspected cause

Probebly the missing library it yells at me for, but I don't know how to fix it... (this is all on mac)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Kaydax** [comment]
Are you on a x64 mac or a M1 mac?

**Comment by Jeffllama123** [comment]
> Are you on a x64 mac or a M1 mac?

I am on x64, In the files it seemed I was on the right version of lwjgl too

**Comment by Jeffllama123** [comment]
> > Are you on a x64 mac or a M1 mac?
> 
> I am on x64, In the files it seemed I was on the right version of lwjgl too

Actually im on M1

**Comment by elan2006** [comment]
Getting the exact same issue here, but I'm on M2 and any instance above 1.20.1 doesn't work. I've tried 1.20.2 and it doesn't work but any instance below 1.20.2 works.

**Comment by elan2006** [comment]
I managed to make it work by changing the version of LWJGL from 3.3.3 to 3.3.1. Also works for 1.21.

**Comment by CrushedAsian255** [comment]
> I managed to make it work by changing the version of LWJGL from 3.3.3 to 3.3.1. Also works for 1.21.

This solution works for me too. Thanks

**Comment by Sneedplex** [comment]
should be fixed please test
