### ISSUE TITLE
Onesix launcher error when trying to launch any instance in 1.2.0

### ISSUE THREAD

**Issue by glowiak** [PolyMC/PolyMC#461]
### Description of bug

suspected cause

### Steps to reproduce

Try to launch anything on 1.2.0

### Suspected cause
```
PolyMC version: 1.2.0-patch-5


Launched instance in online mode

authserver.mojang.com resolves to:
    [52.84.199.41, 52.84.199.46, 52.84.199.60, 52.84.199.53]

session.minecraft.net resolves to:
    [34.192.124.100, 34.197.136.50, 107.23.156.212]

textures.minecraft.net resolves to:
    [65.9.49.113, 65.9.49.103, 65.9.49.23, 65.9.49.119]

api.mojang.com resolves to:
    [54.192.230.47, 54.192.230.107, 54.192.230.48, 54.192.230.46]


Minecraft folder is:
/usr/home/glowiak/.local/share/multimc/instances/Co2/.minecraft


Java path is:
/usr/local/share/minecraft-client/minecraft-runtime


Checking Java version...
Java is version 1.8.0_312, using amd64 architecture, from OpenJDK BSD Porting Team.


hw.model: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz


Main Class:
  

Native path:
  /usr/local/lib/lwjgl

Traits:
traits texturepacks
traits legacyLaunch

Libraries:
  /usr/home/glowiak/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /usr/home/glowiak/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /usr/home/glowiak/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /usr/home/glowiak/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /usr/home/glowiak/.local/share/multimc/instances/Co2/.minecraft/bin/minecraft.jar

Native libraries:

Mods:
  [✔️] buildcraft-client-3.1.6.102
  [✔️] forestry-client-A-1.4.8.6_bc2.2
  [❌] industrialcraft-2-client_1.103.jar (disabled)
  [📁] rei_minimap (folder)
  [📁] sppcommands (folder)

Jar Mods:
  Minecraft_replace (beb82643-a2d9-4e1e-a6a5-1f8214bc2d8b.jar)
  TooManyItems2012_04_13_1.2.5 (0d53215d-9c64-4e6b-9123-020b8db43885.jar)
  ModLoader 1.2.5 (dddae79f-f3ba-4152-a08a-81bb415f7da8.jar)
  ModLoaderMP 1.2.5 v1 (d71467d9-7ccf-48c9-84af-c149a487029f.jar)
  SinglePlayerCommands-MC1.2.5_V3.2.2 (420aeb1c-36fd-4376-9b50-68db0ca81f23.jar)
  [1.2.5]ReiMinimap_v3.2_05 (c3b8589b-bcd3-4d2f-8db7-5ce743182fef.jar)

Params:
  

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 5039


Exception in thread "main" java.lang.ClassFormatError: Invalid constant pool index 0 for field name in class file org/multimc/onesix/OneSixLauncher
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.multimc.EntryPoint.parseLine(EntryPoint.java:68)
	at org.multimc.EntryPoint.listen(EntryPoint.java:106)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	Suppressed: java.io.IOException: CRC error while extracting entry from JAR file
		at sun.misc.URLClassPath$JarLoader$2.getBytes(URLClassPath.java:1007)
		at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
		... 11 more
Proces zakończył z kodem 1.
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
```
CRC error while extracting entry from JAR file
```

that looks like some JAR file is corrupted

**Comment by glowiak** [comment]
But on 1.1.1 it works just normal. And which jar

**Comment by glowiak** [comment]
Oh, I know. Replaced the NewLaunch.jar with this one from 1.1.1 and now everything works as expected.

**Comment by glowiak** [comment]
But I will rebuild the packages anyway to match new patch-5

**Comment by DioEgizio** [comment]
> But on 1.1.1 it works just normal. And which jar

wait actually, i have an idea:
what's your zlib version?

**Comment by DioEgizio** [comment]
because zlib 1.2.12 is causing issues with jar/crc
