### ISSUE TITLE
poly mc cannot run minecraft 1.18.2

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [PolyMC/PolyMC#487]
### Operating System

Linux

### Description of bug

I am using the flatpak version!
so when I run minecraft, this happens, (with forge)
`Cant Find Class: javax/annotation/ParametersAreNonnullByDefault
Cant Find Class: org/slf4j/Logger
Cant Find Class: com/mojang/brigadier/Message
Cant Find Class: com/google/common/util/concurrent/RateLimiter
Cant Find Class: io/netty/channel/SimpleChannelInboundHandler
Cant Find Class: javax/annotation/Nullable
Cant Find Class: com/google/common/collect/Lists
Cant Find Class: com/mojang/logging/LogUtils
Cant Find Class: com/google/gson/reflect/TypeToken
Cant Find Class: com/mojang/authlib/GameProfile
Cant Find Class: com/mojang/authlib/minecraft/UserApiService$UserProperties
Cant Find Class: com/mojang/authlib/minecraft/UserApiService
Cant Find Class: com/mojang/authlib/minecraft/UserApiService$UserFlag
Cant Find Class: com/google/common/util/concurrent/ListeningExecutorService
Cant Find Class: com/google/common/util/concurrent/ListenableFuture
Cant Find Class: com/mojang/authlib/exceptions/AuthenticationUnavailableException
Cant Find Class: com/mojang/authlib/exceptions/InvalidCredentialsException
Cant Find Class: com/mojang/authlib/exceptions/InsufficientPrivilegesException
Cant Find Class: com/mojang/authlib/exceptions/AuthenticationException
Cant Find Class: com/mojang/authlib/minecraft/MinecraftSessionService
Cant Find Class: io/netty/channel/ChannelInitializer
Cant Find Class: com/google/common/base/Splitter
Cant Find Class: io/netty/bootstrap/Bootstrap
Cant Find Class: io/netty/channel/EventLoopGroup
Cant Find Class: io/netty/bootstrap/AbstractBootstrap
Cant Find Class: io/netty/channel/ChannelHandler
Cant Find Class: io/netty/channel/socket/nio/NioSocketChannel
Cant Find Class: io/netty/channel/ChannelFuture
Cant Find Class: com/google/common/collect/ImmutableList
Cant Find Class: com/google/common/net/HostAndPort
Cant Find Class: com/mojang/blocklist/BlockListSupplier
Cant Find Class: it/unimi/dsi/fastutil/objects/Object2ObjectLinkedOpenHashMap
Cant Find Class: com/mojang/datafixers/util/Pair
Cant Find Class: com/google/common/annotations/VisibleForTesting
Cant Find Class: it/unimi/dsi/fastutil/objects/Object2ObjectArrayMap
Cant Find Class: io/netty/buffer/ByteBuf
Cant Find Class: io/netty/util/concurrent/Future
Cant Find Class: io/netty/util/concurrent/GenericFutureListener
Cant Find Class: com/mojang/authlib/minecraft/MinecraftProfileTexture$Type
Cant Find Class: com/mojang/brigadier/arguments/ArgumentType
Cant Find Class: com/mojang/authlib/minecraft/MinecraftProfileTexture
Cant Find Class: com/google/common/collect/Maps
Cant Find Class: com/google/common/base/MoreObjects
Cant Find Class: com/mojang/serialization/Keyable
Cant Find Class: it/unimi/dsi/fastutil/ints/Int2ObjectOpenHashMap
Cant Find Class: it/unimi/dsi/fastutil/ints/Int2ObjectMap
Cant Find Class: com/google/common/collect/Streams
Cant Find Class: com/mojang/bridge/game/GameVersion
Cant Find Class: com/mojang/brigadier/CommandDispatcher
Cant Find Class: com/mojang/authlib/properties/PropertyMap
Cant Find Class: com/mojang/datafixers/DataFixer
Cant Find Class: com/google/common/collect/Queues
Cant Find Class: com/google/common/collect/Sets
Cant Find Class: io/netty/channel/Channel
Cant Find Class: io/netty/channel/ChannelHandlerContext
Cant Find Class: com/mojang/bridge/game/RunningGame
Cant Find Class: io/netty/buffer/Unpooled
Cant Find Class: io/netty/channel/ChannelFutureListener
Cant Find Class: io/netty/channel/ChannelException
Cant Find Class: io/netty/channel/ChannelConfig
Cant Find Class: io/netty/channel/ChannelOption
Cant Find Class: io/netty/channel/ChannelPipeline
Cant Find Class: com/google/common/collect/Iterables
Cant Find Class: it/unimi/dsi/fastutil/ints/IntList
Cant Find Class: it/unimi/dsi/fastutil/ints/IntConsumer
Cant Find Class: com/google/common/collect/AbstractIterator
Cant Find Class: it/unimi/dsi/fastutil/objects/Object2IntMap
Cant Find Class: it/unimi/dsi/fastutil/objects/Object2BooleanFunction
Cant Find Class: it/unimi/dsi/fastutil/objects/Object2IntOpenHashMap
Cant Find Class: com/mojang/authlib/yggdrasil/YggdrasilAuthenticationService
Cant Find Class: com/google/common/collect/PeekingIterator
Cant Find Class: com/google/common/collect/Iterators
Cant Find Class: com/mojang/brigadier/suggestion/Suggestions
Cant Find Class: org/lwjgl/glfw/GLFWErrorCallbackI
Cant Find Class: com/mojang/brigadier/suggestion/SuggestionsBuilder
Cant Find Class: com/mojang/brigadier/context/CommandContext
Cant Find Class: it/unimi/dsi/fastutil/ints/IntArrayList
Cant Find Class: org/lwjgl/util/tinyfd/TinyFileDialogs
Cant Find Class: it/unimi/dsi/fastutil/ints/IntComparator
Cant Find Class: it/unimi/dsi/fastutil/Swapper
Cant Find Class: it/unimi/dsi/fastutil/Arrays`
and so on
this happens without forge, 
`Exception in thread "main" java.lang.ClassFormatError: Unknown constant tag 0 in class file javax/xml/parsers/ParserConfigurationException
	at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1262)
	at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2310)
	at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:140)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:669)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory.getConfiguration(XmlConfigurationFactory.java:46)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:557)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:481)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:323)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:695)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:62)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:355)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:380)
	at com.mojang.logging.LogUtils.getLogger(LogUtils.java:62)
	at net.minecraft.client.main.Main.<clinit>(SourceFile:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)`
the bundled version of java is clearly not working properly

### Steps to reproduce

install 1.18.2 and run it

### Suspected cause

the bundled version of java 17 is broken

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DavidDGTNT** [comment]
Not having this issue with Forge or Fabric.

**Comment by DioEgizio** [comment]
This is weird and I can't reproduce

**Comment by Etaash-mathamsetty** [comment]
guess just arch linux problems even with a flatpak ????

**Comment by Etaash-mathamsetty** [comment]
ok clearing data and reinstalling fixed it...
that was wierd
