### ISSUE TITLE
Problem with Crash Landing Modpack

### ISSUE THREAD

**Issue by mahyarmirrashed** [PolyMC/PolyMC#853]
### Version of PolyMC

PolyMC - Version 1.3.2-404b9599

### Description of bug

For Minecraft to launch. Instead, I get this log:

```
PolyMC version: 1.3.2-404b9599


Launched instance in offline mode

Minecraft folder is:
/home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/instances/Crash Landing/minecraft


Java path is:
/app/jdk/8/jre/bin/java


Checking Java version...
Java is version 1.8.0_332, using amd64 architecture, from Oracle Corporation.


11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/instances/Crash Landing/natives

Libraries:
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/argo/argo/2.25_fixed/argo-2.25_fixed.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/com/google/guava/guava/14.0/guava-14.0.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/net/minecraftforge/forge/1.6.4-9.11.1.965/forge-1.6.4-9.11.1.965-universal.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/net/minecraft/launchwrapper/1.8/launchwrapper-1.8.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/com/mojang/minecraft/1.6.4/minecraft-1.6.4-client.jar

Native libraries:
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Mods:
  [📁] 1.6 (folder)
  [✔️] 1.6.4-SortFix-1.0
  [✔️] appeng-rv14-finale3-mc16x
  [✔️] autopackager-1.4
  [✔️] autoutils-1.6.4-1.0.1
  [✔️] BigReactors-0.3.4A2
  [✔️] ChickenChunks-1.6.4-1.3.3.4-universal
  [✔️] chisel-1.6.4-1.5.2
  [✔️] CodeChickenCore-1.6.4-0.9.0.9-universal
  [✔️] CoFHCore-2.0.0.5
  [✔️] ConfigMod for MC v1.6.4
  [✔️] CoroUtil for MC v1.6.4
  [✔️] crowley-skyblock-v1.29e
  [✔️] CustomChestLoot 1.1 for MC 1.6.2
  [❌] EnderIO-1.6.4-1.0.6.376.jar (disabled)
  [✔️] EnviroMine-v1.1.89
  [✔️] ExtraCells-1.6.9d
  [✔️] extrautils-1.0.3c
  [✔️] Generator_mods_0.1.4(1.6.X)
  [✔️] HarvestCraftWaila-mc1.6.4-1.0.4
  [✔️] hungeroverhaul-1.6.X-2l-build4
  [✔️] InventoryTweaks-MC1.6.2-1.56-b77
  [✔️] ironchest-universal-1.6.4-5.4.1.702
  [✔️] launchgui-1.6.4-1.3
  [✔️] Lockdown-universal-1.6.4-1.0.0.0
  [✔️] MineFactoryReloaded-2.7.9-final
  [✔️] ModTweaker-1.6.4-0.3
  [✔️] neiaddons-mc164-1.10.5.70
  [✔️] NEIPlugins-1.1.0.6
  [✔️] NotEnoughItems-1.6.4-1.6.1.9-universal
  [✔️] NotEnoughKeys-1.6.4-0.0.4
  [✔️] OpenBlocks-1.2.8
  [✔️] OpenModsLib-0.5
  [✔️] Pam's HarvestCraft 1.6.4 v1.1.4
  [✔️] PneumaticCraft 1.1.4f
  [✔️] PowerCrystalsCore-1.1.8-9
  [✔️] RedstoneArsenal-1.0.0.0
  [📁] resources (folder)
  [✔️] rockdigger-1.3-1.6.4
  [✔️] ruins
  [✔️] Ruins_1.6.4
  [✔️] ruins_log
  [✔️] SimplyJetpacks-0.3.1
  [❌] SpecialAI 1.0 PRE for MC 1.6.4.zip (disabled)
  [✔️] SpecialMobs 3.0 for MC 1.6.2
  [✔️] SpiceOfLife-mc1.6.4-1.0.3c
  [✔️] Steve's Drought 4
  [✔️] StevesFactoryManagerA83
  [✔️] TConstruct_mc1.6.4_1.5.5.7
  [✔️] ThermalExpansion-3.0.0.7
  [✔️] TiCTooltips-mc1.6.4-1.1.8
  [✔️] tictweaks-1.6.4-1.0.3
  [✔️] TMechworks_mc1.6.4_0.1.6
  [✔️] TSteelworks-mc1.6.4_0.0.4.2-fix2
  [✔️] UpdateCheckerMod_1.6.4
  [📁] VoxelMods (folder)
  [✔️] WailaHarvestability-mc1.6.4-1.0.3
  [✔️] ZansMinimap1.6.4
  [✔️] zMineTweaker-1.6.4-2.3.1
  [✔️] zombieawareness for MC v1.6.4

Params:
  --username  --session  --version 1.6.4 --gameDir /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/instances/Crash Landing/minecraft --assetsDir /home/asdf/.var/app/org.polymc.PolyMC/data/PolyMC/assets/virtual/legacy --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 1264


Jun 28, 2022 5:04:45 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
Jun 28, 2022 5:04:45 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
Jun 28, 2022 5:04:45 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
2022-06-28 17:04:45 [INFO] [ForgeModLoader] Forge Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading
2022-06-28 17:04:45 [INFO] [ForgeModLoader] Java is OpenJDK 64-Bit Server VM, version 1.8.0_332, running on Linux:amd64:5.18.6-200.fc36.x86_64, installed at /app/jdk/8/jre
2022-06-28 17:04:45 [WARNING] [ForgeModLoader] The coremod net.minecraftforge.lex.sortfix.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2022-06-28 17:04:45 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2022-06-28 17:04:45 [WARNING] [ForgeModLoader] The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2022-06-28 17:04:45 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2022-06-28 17:04:46 [WARNING] [ForgeModLoader] The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2022-06-28 17:04:46 [WARNING] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2022-06-28 17:04:46 [WARNING] [ForgeModLoader] The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2022-06-28 17:04:46 [WARNING] [ForgeModLoader] The coremod openmods.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2022-06-28 17:04:46 [WARNING] [ForgeModLoader] The coremod squeek.spiceoflife.asm.ASMPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2022-06-28 17:04:46 [WARNING] [ForgeModLoader] The coremod tconstruct.preloader.TConstructLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2022-06-28 17:04:46 [INFO] [TCon-Preloader] Scalpel. Suction. Lumber axe. CLEAR! *zap*
2022-06-28 17:04:46 [INFO] [TCon-Preloader] Constructing preloader (Modules: [tconstruct.preloader.AccessTransformers, tconstruct.preloader.ASMInterfaceRepair])
2022-06-28 17:04:46 [INFO] [TCon-Preloader] Found a properties file. Attempting load...
2022-06-28 17:04:46 [INFO] [TCon-Preloader] Loaded properties successfully. Using specified settings.
2022-06-28 17:04:46 [WARNING] [ForgeModLoader] The coremod appeng.transformer.AppEngCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2022-06-28 17:04:46 [INFO] [ForgeModLoader] [AppEng] Core Init
2022-06-28 17:04:46 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2022-06-28 17:04:46 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
2022-06-28 17:04:46 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2022-06-28 17:04:46 [SEVERE] [ForgeModLoader] Unable to launch
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.remove(ArrayList.java:875)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
Process exited with code 0.
```

### Steps to reproduce

Just create a new instance, go to Crash Landing in the Curseforge tab, and attempt to run. It doesn't matter if you run locally or online, it'll crash both ways.

### Suspected cause

[This](https://www.reddit.com/r/feedthebeast/comments/2jb5kk/crash_landing_not_working/) Reddit post describes it as being a bug with CurseForge 1.6.x that resulted in these sorts of exceptions. The link in the Reddit post points to a [patch](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2206446-forge-1-6-4-1-7-2-java-8-compatibility-patch) that does some magickery with the Java classes.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by mahyarmirrashed** [comment]
Perhaps, what can be done, is to add an additional script for the `1.6.x` downloads from CurseForge that will apply the patch automatically.

**Comment by DioEgizio** [comment]
You need LegacyJavaFixer

**Comment by mahyarmirrashed** [comment]
> You need LegacyJavaFixer

Do you have a link to the mod on SourceForge? Not sure what to do exactly.

**Comment by DioEgizio** [comment]
> > You need LegacyJavaFixer
> 
> Do you have a link to the mod on SourceForge? Not sure what to do exactly.

https://dist.creeper.host/FTB2/maven/net/minecraftforge/lex/legacyjavafixer/1.0/legacyjavafixer-1.0.jar

**Comment by mahyarmirrashed** [comment]
I ran it and it still fails on the Ex Aliquo modpack. Not sure if that has ore to do with Forge itself at this point or PolyMC. If it's the former, please feel free to close this issue.

**Comment by stvev1337** [comment]
Apparently this pack requires Java 7, but I think PolyMC doesn't work with 7. Legacy Java Fixer has little information on its curseforge page, and requires -Dfml.ignoreInvalidMinecraftCertificates=true to allow "tampering with minecraft" which polymc would otherwise prevent to keep the user safe from malware.
Also, this pack falsely reports requiring java 8 in the polymc logs.
